name: validation

on:
  push:
  pull_request:

jobs:
  portable-regressions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: >-
          cmake -S contrib/validation -B build.validation -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Werror"
      - name: Build
        run: cmake --build build.validation
      - name: Test
        run: ctest --test-dir build.validation --output-on-failure
